name        = 'Minimal-White'
license     = 'MIT'
licenselink = 'https://github.com/egeorjon/Minimal-White/LICENSE'
description = 'Clean, configurable and responsive Hugo theme'

# The home page of the theme, where the source can be found
homepage    = 'https://github.com/egeorjon/Minimal-White'

# If you have a running demo of the theme
demosite    = 'https://emmanuelgeorjon.com/'

# Taxonomy terms
tags = [
  "responsive",
  "simple",
  "clean",
  "light",
  "blog",
  "widget",
  "minimalist"
]

features = [
  "responsive",
  "blog",
  "table-of-contents",
  "opengraph",
  "favicon",
  "share-icons",
  "gallery",
  "cover",
  "multilingual",
  "social-icons",
  "minified-assets",
  "search"
]

min_version = "0.140.2"

# If the theme has a single author
[author]
  name     = 'Emmanuel GEORJON'
  homepage = 'https://emmnauelgeorjon.com/'
